# name: Run Cypress Tests in Docker

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   cypress-run:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Check out repository
#         uses: actions/checkout@v3

#       - name: Set up Docker
#         run: |
#           docker --version
#           sudo apt-get update
#           sudo apt-get install -y docker-compose
#           docker-compose --version

#       - name: Build Docker image with Cypress
#         run: |
#           docker build -t cypress-tests .

#       - name: Run Cypress tests in Docker container
#         run: |
#           docker run -v ${{ github.workspace }}:/cypress/e2e/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1 \
#             npx cypress run

#       - name: Run tests inside Docker
#         run: docker run --rm cypress-tests || echo "Tests failed, but continuing workflow."
#         continue-on-error: true
name: Run Cypress Tests in Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          docker --version
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker-compose --version

      - name: Build Docker image with Cypress
        run: |
          docker build -t cypress-tests .

      - name: Run Cypress tests inside Docker container
        run: |
          docker run --rm -v ${{ github.workspace }}:/cypress cypress-tests npx cypress run --browser chrome --headless
          # Вказуємо, що тести знаходяться в папці e2e всередині /cypress
          # Або можна явно вказати шлях до тестів
          # docker run --rm -v ${{ github.workspace }}:/cypress cypress-tests npx cypress run --spec "cypress/e2e/**/*.cy.js" --browser chrome --headless

      - name: (Optional) Store Cypress test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-results
          path: cypress/results
          retention-days: 7

      - name: (Optional) Store Cypress screenshots and videos
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-artifacts
          path: cypress/screenshots cypress/videos
          retention-days: 7